name: Go Unit Tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: sudo systemctl start nginx
    - run: sudo systemctl status nginx
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11.6' 

    - name: Python test
      run: |
        export PORT=8123
        echo "Deploying to port $PORT..."
        cd ./examples/python-server
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        python app.py

    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test with the Go CLI
      run: go test -exec sudo -v ./...